---
plugins:
  duplication:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      extensions:
      - .js
      - .jsx
      - .ts
      - .tsx
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.md"
exclude_paths:
- .expo/
- .github/
- assets/
- coverage/
- docs/
- node_modules/
- scripts/
- src/config/normalize.js
- .codeclimate.yml
- .eslintrc
- .gitignore
- .nvmrc
- .yvmrc
- babel.config.js
- "*.png"
- jest-setup.js
- yarn.lock
